'use client';

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 30,
  },
  header: {
    marginBottom: 20,
    borderBottom: 1,
    borderBottomColor: '#2563EB',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    color: '#2563EB',
    fontWeight: 'bold',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 5,
  },
  section: {
    margin: 10,
    padding: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#1E40AF',
  },
  table: {
    width: 'auto',
    marginBottom: 10,
    borderStyle: 'solid',
    borderColor: '#bfbfbf',
    borderWidth: 1,
  } as const,
  tableRow: {
    flexDirection: 'row',
    borderBottomColor: '#bfbfbf',
    borderBottomWidth: 1,
  },
  tableHeader: {
    backgroundColor: '#f3f4f6',
    color: '#374151',
    padding: 5,
    fontWeight: 'bold',
  },
  tableCell: {
    padding: 5,
    fontSize: 12,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    color: '#666666',
    fontSize: 10,
  },
});

interface PharmCatReportProps {
  data: {
    patientId?: string;
    reportDate: string;
    phenotypes: Array<{
      gene: string;
      phenotype: string;
      activity: string;
      implications: string;
    }>;
    recommendations: Array<{
      drug: string;
      recommendation: string;
      severity: 'high' | 'medium' | 'low';
    }>;
  };
}

export default function PharmCatReport({ data }: PharmCatReportProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>RxBlueprint Pharmacogenomic Report</Text>
          <Text style={styles.subtitle}>Patient ID: {data.patientId || 'Not provided'}</Text>
          <Text style={styles.subtitle}>Report Date: {data.reportDate}</Text>
        </View>

        {/* Phenotypes Section */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Genetic Phenotypes</Text>
          <View style={styles.table}>
            <View style={[styles.tableRow, styles.tableHeader]}>
              <Text style={{ flex: 1 }}>Gene</Text>
              <Text style={{ flex: 2 }}>Phenotype</Text>
              <Text style={{ flex: 1 }}>Activity</Text>
            </View>
            {data.phenotypes.map((item, index) => (
              <View key={index} style={styles.tableRow}>
                <Text style={[styles.tableCell, { flex: 1 }]}>{item.gene}</Text>
                <Text style={[styles.tableCell, { flex: 2 }]}>{item.phenotype}</Text>
                <Text style={[styles.tableCell, { flex: 1 }]}>{item.activity}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Recommendations Section */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Drug Recommendations</Text>
          <View style={styles.table}>
            <View style={[styles.tableRow, styles.tableHeader]}>
              <Text style={{ flex: 1 }}>Drug</Text>
              <Text style={{ flex: 2 }}>Recommendation</Text>
              <Text style={{ flex: 1 }}>Severity</Text>
            </View>
            {data.recommendations.map((item, index) => (
              <View key={index} style={styles.tableRow}>
                <Text style={[styles.tableCell, { flex: 1 }]}>{item.drug}</Text>
                <Text style={[styles.tableCell, { flex: 2 }]}>{item.recommendation}</Text>
                <Text style={[styles.tableCell, { flex: 1 }]}>{item.severity}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text>Generated by RxBlueprint • {new Date().toLocaleDateString()}</Text>
          <Text>This report should be reviewed by a healthcare professional</Text>
        </View>
      </Page>
    </Document>
  );
}
